#!/usr/bin/env python
import os
import pyperclip
import sys


def main() -> None:
    raw_output: str = os.popen('colorpicker --one-shot').read()
    if '#' not in raw_output:
        sys.exit(0)
    pyperclip.copy(parse_output(raw_output))


def parse_output(raw: str) -> str:
    tokens = raw.split()
    return tokens[len(tokens) - 1]


if __name__ == '__main__':
    main()
