#!/usr/bin/env python
import os
import sys
import time

configs: list[str] = [os.path.expanduser(path) for path in [
    '~/.config/polybar/config.ini',
    '~/.config/bspwm/bspwmrc',
    '~/.config/dunst/dunstrc',
    '~/.config/ncspot/config.toml',
    '~/.config/rofi/custom_theme.rasi',
    '~/st/config.h',
]]

def main():
    if len(sys.argv) != 2:
        usage()
        sys.exit(1)
    theme_id = sys.argv[1]
    for config in configs:
        print(os.popen(f'patch-config-theme {config} {theme_id}').read().rstrip('\n'))
    _ = os.popen('killall dunst')
    _ = os.popen('bspc wm -r')
    _ = os.system(f'sudo make install --directory={os.path.expanduser('~/st/')}')
    _ = os.popen('notify-send "system theme applied"')       


def usage():
    print('Usage: not this')
    _ = ()

if __name__ == '__main__':
    main()
