#!/usr/bin/env python3
import sys
import os
import subprocess

_DEFAULT_SCRIPTS_DIR = os.path.expanduser("~/.config/scripts/wallpaperctl_scripts/")


def change_wallpaper_source(args: list[str]) -> None:
    script_path = os.path.join(_DEFAULT_SCRIPTS_DIR, 'change_wallpaper_source')
    _ = subprocess.run([script_path] + args)


def next_wallpaper(args: list[str]) -> None:
    script_path = os.path.join(_DEFAULT_SCRIPTS_DIR, 'change_wallpaper')
    _ = subprocess.run([script_path] + args)


def load_last_wallpaper(args: list[str]) -> None:
    script_path = os.path.join(_DEFAULT_SCRIPTS_DIR, 'load_last_wallpaper')
    _ = subprocess.run([script_path] + args)


def get_wallpaper_source(args: list[str]) -> None:
    script_path = os.path.join(_DEFAULT_SCRIPTS_DIR, 'get_wallpaper_source')
    _ = subprocess.run([script_path] + args)


def clear_cache(args: list[str]) -> None:
    script_path = os.path.join(_DEFAULT_SCRIPTS_DIR, 'clear_cache')
    _ = subprocess.run([script_path] + args)


def usage() -> None:
    print('Usage: wallpaperctl <command> [args]')
    print('Commands:')
    print('  change [image_file_path|folder_path] - Change the wallpaper/folder')
    print('  next - Change to the next wallpaper from the folder')
    print('  last - Load the last wallpaper')
    print('  get - Get current wallpaper source')
    print('  clear - Clear the blurred images cache')


def main():
    if len(sys.argv) <= 1:
        usage()
        sys.exit(1)
    command = sys.argv[1]
    args = sys.argv[2:]

    if command == 'change':
        change_wallpaper_source(args)
    elif command == 'next':
        next_wallpaper(args)
    elif command == 'last':
        load_last_wallpaper(args)
    elif command == 'get':
        get_wallpaper_source(args)
    elif command == 'clear':
        clear_cache(args)
    else:
        print(f'Unknown command: {command}')
        usage()
        sys.exit(1)


if __name__ == '__main__':
    main()
