Section "InputClass"
    Identifier "touchpad catchall"
    Option "Tapping" "on"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0.4"
    Option "DisableWhileTyping" "true"
    Option "HorizontalScrolling" "true"
    Option "MiddleEmulation" "true"
    Option "NaturalScrolling" "true"
    Option "ScrollMethod" "twofinger"
EndSection
