#!/usr/bin/env python3
import wallpaper_util as util
import sys

def main():
    if len(sys.argv) != 1:
        print('Usage: next')
        sys.exit(1)
    change_to_next_wallpaper()

def change_to_next_wallpaper() -> None:
    if util.is_wallpaper(util.get_wallpaper_source()):
        util.set_wallpaper(util.get_wallpaper_source())
        return
    more_than_one_wallpaper = len(util.get_image_files(util.get_wallpaper_source())) >= 1
    new_wallpaper = util.get_next_wallpaper()
    while new_wallpaper == util.get_last_wallpaper() and more_than_one_wallpaper:
        new_wallpaper = util.get_next_wallpaper()
    util.set_wallpaper(new_wallpaper)


if __name__ == "__main__":
    main()
