#!/usr/bin/env python3
import sys
import os
import wallpaper_util as util

def main():
    if len(sys.argv) != 2:
        print('Usage: change [image_file_path|folder_path]')
        sys.exit(1)
    new_source_path = os.path.abspath(sys.argv[1])
    if not os.path.exists(new_source_path):
        print(f'Path does not exist: {new_source_path}')
        sys.exit(1)
    if util.get_wallpaper_source() == new_source_path or util.get_wallpaper_source() == new_source_path + '/':
        print(f'Already using {new_source_path}')
        sys.exit(0)

    if os.path.isdir(new_source_path) and not new_source_path.endswith('/'):
        new_source_path += "/"

    write_source_to_cache(new_source_path)
    delete_blurred_images_cache()
    os.system(f'{util.scripts_folder}bake_blurred_wallpapers')
    os.system(f'{util.scripts_folder}change_wallpaper')

def write_source_to_cache(folder_path: str) -> None:
    with open(util.wallpaper_source_cache, 'w') as file:
        file.write(folder_path)

def delete_blurred_images_cache():
    if not os.path.exists(util.blurred_images_folder):
        return
    if len(os.listdir(util.blurred_images_folder)) == 0:
        return
    os.system(f'rm {util.blurred_images_folder}*')


if __name__ == '__main__':
    main()
