#!/usr/bin/env python3
import sys
import wallpaper_util as util

def main():
    if len(sys.argv) != 1:
        print('Usage: get')
        sys.exit(1)
    if not util.is_valid_wallpaper_source(util.get_wallpaper_source()):
        print(f'{util.get_wallpaper_source()} is not a valid wallpaper source')
        sys.exit(0)
    print(util.get_wallpaper_source())

if __name__ == '__main__':
    main()