#!/bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#11111B

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI2"

# on first load setup
if [[ "$1" = 0 ]]; then
    /home/benkenobi/.config/bspwm/scripts/autostart &

	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		echo "configuring double-monitor"
		bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 0
		bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
		xrandr --output "$INTERNAL_MONITOR" --mode 1920x1080 --pos 0x0 --rotate normal --output "$EXTERNAL_MONITOR" --primary --mode 1920x1080 --pos 1920x0 --rotate normal
	else
		echo "configuring single-monitor"
		bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
		xrandr --output "$INTERNAL_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal 
	fi
fi

