#!/bin/sh
INTERNAL_MONITOR="$(bspc query -M --names)"

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

xset r rate 250 40
setxkbmap de
xrandr --output $INTERNAL_MONITOR --dpi 140

bspc config border_width 4
bspc config window_gap 10
bspc config normal_border_color "#585b70"
bspc config focused_border_color "#BAC2DE"

bspc config split_ratio 0.5

# on first load setup
if [[ "$1" = 0 ]]; then
	/home/benkenobi/.config/bspwm/scripts/autostart &
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
fi

