#!/bin/sh
INTERNAL_MONITOR="$(bspc query -M --names)"

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

xset r rate 250 40
setxkbmap de
xrandr --output $INTERNAL_MONITOR --dpi 140

bspc config border_width 0
bspc config window_gap 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config presel_feedback_color \#11111B

# on first load setup
if [[ "$1" = 0 ]]; then
	/home/benkenobi/.config/bspwm/scripts/autostart &
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
fi

