use_nerdfont = true
flip_status_indicators = true
volnorm = true
gapless = false
repeat = "playlist"
cover_max_scale = 4
library_tabs = ["playlists", "tracks", "albums", "artists"]
statusbar_format = "%title - %artists"

[track_format]
left = "%title"
center = "%album (%artists)"
right = "%saved %duration"

[keybindings]
n = "next"
p = "previous"
Space = "playpause"
"Shift+Esc" = "quit"
"Shift+s" = "focus search"
Esc = "back"
"Shift+l" = "focus library"
"Shift+c" = "focus cover"
"Shift+q" = "focus queue"
Left = "noop"
Right = "noop"
Up = "noop"
Down = "noop"
F8 = "noop"

[theme]
primary = "#DFEFF5"
secondary = "#949FA4"
title = "#67C1FF"
playing = "#67C1FF"
playing_selected = "#030A17"
error = "#FF3571"
statusbar = "#67C1FF"
statusbar_progress = "#67C1FF"
cmdline = "#67C1FF"
highlight = "#030A17"
highlight_bg = "#67C1FF"
