#!/bin/sh
#Picom (seems to create second bspwm monitor when running with external?)
killall picom
picom -b --no-fading-openclose

#Status bars
polybar --reload --quiet &

#python /home/benkenobi/.config/bspwm/scripts/handle_focus.py &

python /home/benkenobi/.config/bspwm/scripts/load_background.py

#lock-screen
killall xss-lock
xset s 600
xss-lock -- /home/benkenobi/.config/bspwm/scripts/lock_script &

