#!/bin/sh
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

python /home/benkenobi/.config/bspwm/scripts/kill_scripts_on_startup.py

#Picom
killall picom
picom -b --no-fading-openclose
#picom -b --no-fading-openclose --inactive-dim 0.3333

#Status bars
killall eww
eww daemon &
#bar-scripts
INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI2"
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	eww open bar_main &
	eww open bar_side &
	eww open darkbar_main &
	eww open darkbar_side &
else
	eww open bar_main &
	eww open darkbar_main &
fi
python /home/benkenobi/.config/bspwm/scripts/handle_eww_bar.py &
#update brightness
/home/benkenobi/.config/bspwm/scripts/ChangeBrightness increase 0
python /home/benkenobi/.config/bspwm/scripts/handle_focus.py &

#Background
/home/benkenobi/.config/bspwm/scripts/update_backgrounds &

#lock-screen
xset s 600
xss-lock -- /home/benkenobi/.config/bspwm/scripts/lock_script

