#!/bin/bash
operator="$1"
value=$2

if [ "$operator" = "increase" ]
then
	idk=$(brightnessctl set +$value%)
fi


if [ "$operator" = "decrease" ]
then
    idk=$(brightnessctl set $value%-)
fi

brightness=$(/home/benkenobi/.config/bspwm/scripts/GetBrightness)
exec eww update brightness=$brightness
