#! /bin/sh

chosen=$(printf "  Power Off\n  Reboot\n󰍃  Log Out\n  Lock" | rofi -dmenu -i -theme-str 'prompt { enabled: false; }')

case "$chosen" in
	"  Power Off") poweroff ;;
	"  Reboot") reboot ;;
	"󰍃  Log Out") bspc quit ;;
	"  Lock") betterlockscreen -l blur ;;
	*) exit 1 ;;
esac
