[global/wm]
include-file = /home/benkenobi/.config/polybar/mocha.ini

#dont know why importing does not work
[colors]
background = #C0000000
background-alt = ${colors.base}
foreground = ${colors.text}
primary = ${colors.sapphire}
secondary = ${colors.sapphire}
alert = ${colors.red}
disabled = ${colors.subtext0}
low = ${colors.green}
medium = ${colors.yellow}
high = ${colors.red}

[bar/example]
width = 100%
height = 24pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "FiraCode Nerd Font:style=Bold;3"
font-1 = "Source Han Sans JP,源ノ角ゴシック JP:style=Bold;3"
font-2 = monospace;2

modules-left = i3
modules-center = xwindow
modules-right = pulseaudio backlight battery wlan date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = none

; wm-restack = generic
; wm-restack = bspwm
wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %icon%
#label-active-background = ${colors.background}
label-active-background = #ff0000
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %icon%
label-occupied-padding = 1

label-urgent = %icon%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %icon%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = ""
format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>

ramp-volume-0 = %{F#a6e3a1}󰕿 
ramp-volume-1 = %{F#f9e2af}󰖀
ramp-volume-2 = %{F#f38ba8}󰕾 

label-volume = %percentage%%

#label-muted = %{F#a6adc8}󰝟
label-muted = %{F#a6adc8}󱄡
label-muted-foreground = ${colors.disabled}

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
#label-connected = %{F#74c7ec}%ifname%%{F-} %essid%
label-connected = %essid%
format-connected-background = ${colors.background}
format-connected-padding = 1

[module/date]
type = internal/date
interval = 1

date = %d-%m-%Y %H:%M:%S
date-alt = %H:%M

label = %date%
label-foreground = ${colors.primary}

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp> <label>

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used
; "", "", "", "", "", "", "", "", ""
ramp-0 = %{F#a6e3a1}
ramp-1 = %{F#a6e3a1}
ramp-2 = %{F#a6e3a1}
ramp-3 = %{F#89b4fa}
ramp-4 = %{F#89b4fa}
ramp-5 = %{F#89b4fa}
ramp-6 = %{F#f38ba8}
ramp-7 = %{F#f38ba8}
ramp-8 = %{F#f38ba8}

; Only applies if <bar> is used
bar-width = 10
bar-indicator = |
bar-fill = ─
bar-empty = ─

[module/battery]
type = internal/battery
; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 100

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 15

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5


;"", "", "", "", ""
ramp-capacity-0 = %{F#f38ba8}
ramp-capacity-1 = %{F#f9e2af}
ramp-capacity-2 = %{F#a6e3a1}
ramp-capacity-3 = %{F#a6e3a1}
ramp-capacity-4 = %{F#a6e3a1}
ramp-capacity-5 = %{F#a6e3a1}

label-discharging = %percentage%%

format-discharging = "<ramp-capacity>  <label-discharging>"

[module/i3]
type = internal/i3

; ws-icon-[0-9]+ = <label>;<icon>
; NOTE: The <label> needs to match the name of the i3 workspace
; Neither <label> nor <icon> can contain a semicolon (;)
ws-icon-0 = 1;一
ws-icon-1 = 2;二
ws-icon-2 = 3;三
ws-icon-3 = 4;四
ws-icon-4 = 5;五
ws-icon-5 = 6;六
ws-icon-6 = 7;七
ws-icon-7 = 8;八
ws-icon-8 = 9;九
ws-icon-9 = 10;十
ws-icon-default = ~
; NOTE: You cannot skip icons, e.g. to get a ws-icon-6
; you must also define a ws-icon-5.
; NOTE: Icon will be available as the %icon% token inside label-*

; Available tags:
;   <label-state> (default) - gets replaced with <label-(focused|unfocused|visible|urgent)>
;   <label-mode> (default)
format = <label-state> <label-mode>

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 2
label-mode-background = #e60053

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %icon%
label-focused-foreground = #cdd6f4
label-focused-background = #11111b
label-focused-underline = #74c7ec
label-focused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %icon%
label-unfocused-padding = 2

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %icon%
label-visible-underline = #555555
label-visible-padding = 4

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #f38ba8
label-urgent-padding = 2

; Separator in between workspaces
label-separator = |
label-separator-padding = 0
label-separator-foreground = #cdd6f4

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
